# NOTE FOR LOCAL DEVELOPMENT AND TESTING:
# This file is used by Docker Compose to set up the local development environment.
# It is not used in production. For production, we use Terraform to provision
