name: Terraform Deploy to GCP

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "Terraform/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: Terraform/
            shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
       
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Cleanup tfvars
        run: rm -f terraform.tfvars
